layout_spectrum: 1
typography_spectrum: 0.09498208
color:
  saturation: 0.8204871
  lightness: 0.3474361
  brandStrength: 0.04920584
  rhythmicContrast: 0.7825188
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Elcatrinylacatrinthe
